#!/bin/bash

currentlyPlaying=$(rhythmbox-client --print-playing) 
#currentlyPlaying=$(rhythmbox-client --print-playing --print-playing-format "%ta - %tt (%te / %td)") 

playingState=$(gdbus call --session --dest org.mpris.MediaPlayer2.rhythmbox --object-path /org/mpris/MediaPlayer2 --method org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player PlaybackStatus | grep "Playing")

toggleIcon=""
if [ -z "$playingState" ]; then
	toggleIcon=""
else
	toggleIcon=""
fi

shuffleState=$(gdbus call --session --dest org.mpris.MediaPlayer2.rhythmbox --object-path /org/mpris/MediaPlayer2 --method org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player Shuffle | grep "true")
shuffleIcon=" "
if [ -z "$shuffleState" ]; then
	shuffleIcon=""
fi

loopState=$(gdbus call --session --dest org.mpris.MediaPlayer2.rhythmbox --object-path /org/mpris/MediaPlayer2 --method org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player LoopStatus | grep "None")
loopIcon=" "
if [ ! -z "$loopState" ]; then
	loopIcon=""
fi

MENU="$(rofi -sep "|" -dmenu -i -p "$currentlyPlaying$loopIcon$shuffleIcon" -theme ~/.cache/wal/colors-rofi-dark.rasi -location 0 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "$toggleIcon Toggle Play/Pause| Next| Previous| Stop")"
#MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *"Toggle Play/Pause") rhythmbox-client --play-pause ;;
				*Stop) rhythmbox-client --stop ;;
				*Next) rhythmbox-client --next ;;
				*Previous) rhythmbox-client --previous ;;
            esac
